src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }
}

templates/Tech/technicien.html.twig
{% extends 'techbase.html.twig' %}

{% block body %}
<h5>Technicien</h5>
</br>
{% if tickets|length > 0 %}
     <table style="margin-top : 30px;padding: 2px;" class="table table-hover">
            <thead>
              <tr class="table-primary">
                <th>Titre</th>
                <th>Categorie</th>
                <th>Etat</th>
                <th>Date de creation</th>
                <th>Technicien</th>
              </tr>
              </thead>
              <tbody style="background-color : white;">
                {% for ticket in tickets %}
                        <tr style="font-color = Black;">
                            <td>
                            {{ ticket.title }}
                            </td>
                            <td>
                            {{ ticket.Categorie }}
                            </td>
                            <td>
                            <form action="{{ path('tech_home',{'id': ticket.id }) }}" method="post" name="form_etat">
                                <select class="form-control" name="etats" onchange="this.form.submit()">
                                <option disabled selected value> -- select an option -- </option>
                                        {% for etat in etats %}
                                            <option value="{{ etat.titre }}">{{ etat.titre }}</option>
                                        {% endfor %}
                                </select>
                            </form>
                            </td>
                            <td >
                            {{ ticket.createdAt | date('Y-m-d H:i')}}
                            </td>
                            
                            <td >
                                {{ ticket.technicien.Nom }} {{ ticket.technicien.prenom }} 
                            </td>
                        </tr>
                    
                {% endfor %}  
              <tbody> 
            </table>
            {% else %}
                <h5>  No results <h5>
            {% endif %} 
{% endblock %}